/// Generated by AssetsRefGenerator on 2020/10/22
class Res {
  static const String appicon = "assets/icon/appicon.png";
  static const String boy = "assets/images/boy.png";
  static const String couple = "assets/images/couple.png";
  static const String girl = "assets/images/girl.png";
  static const String mortarboard = "assets/images/mortarboard.png";
  static const String stickman = "assets/images/stickman.png";
}
